---
namespace: iac
name: molecule
version: 1.0.0
readme: README.md
authors:
  - Manas Maiti <mmaiti@redhat.com>

description: An example collection to test Ansible with Molecule
license:
  - GPL-2.0-or-later
