---
- name: Ensure SSH is installed
  ansible.builtin.yum:
    name:
      - openssh-server
    state: installed
  notify: Start and enable sshd

- name: Ensure SSH configuration is complaint
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
   