---
name: CI for ansible test
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Yamllint
        run: yamllint .
  molecule:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "enterpriselinux"
            tag: "latest"
    steps:
      - uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      #     cache: 'pip'
      #     cache-dependency-path: '**/requirements*.txt'
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      # - name: Molecule test SSH
      #   run: cd ./roles/ssh && molecule test
      # - name: Molecule test APP
      #   run: cd ./roles/app && molecule test
      - name: Molecule
        uses: robertdebock/molecule-action@5.0.2
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
        env:
          ANSIBLE_ROLES_PATH: roles/app
  build-ee:
    needs:
      - molecule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: pip install --upgrade ansible-core ansible-builder ansible-navigator
      - name: Build EE
        run: ansible-builder build -t custom
