---
name: CI for ansible test
on:
  - push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Yamllint
        run: yamllint .
      - name: Molecule converge
        run: molecule converge
      - name: Molecule verify
        run: cd roles/ssh && molecule verify
