---
name: CI for ansible test
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Yamllint
        run: yamllint .
  molecule:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install podman
        run: apt-get update && apt-get install -y podman
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Molecule converge SSH
        run: cd ./roles/ssh && molecule test
      - name: Molecule converge APP
        run: cd ./roles/app && molecule test
  build-ee:
    needs:
      - molecule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Install dependencies
        run: pip install --upgrade ansible-core ansible-builder ansible-navigator
      - name: Build EE
        run: ansible-builder build -t custom
